export { default as HomePage } from "./home";
export { default as SignInPage } from "./sign-in";
export { default as SignUpPage } from "./sign-up";
export { default as PageNotFoundPage } from "./page-not-found";
export { default as ForgotPasswordPage } from "./forgot-password";
export { default as ResetPasswordPage } from "./reset-password";
export { default as Cart } from "./cart";
export { default as PaymentSuccess } from "./payments/Success";
export { default as PaymentFailed } from "./payments/Failed"
export { default as OrderSuccess } from "./order/OrderSuccess"